# CodeRabbit 설정 파일
reviews:
  auto_review: true
  
  # 리뷰 대상 파일 패턴
  include_patterns:
    - "**/*.{js,ts,jsx,tsx}"
    - "**/*.{py,java,go,cpp,c,cs}"
    - "**/*.{yml,yaml,json,md}"
  
  # 리뷰 제외 파일 패턴
  exclude_patterns:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "*.min.js"
    - "coverage/**"
    - "vendor/**"
    - ".git/**"

# 리뷰 설정
review_settings:
  thoroughness: "medium"
  
  focus_areas:
    - "security"
    - "performance" 
    - "maintainability"
    - "testing"
    - "documentation"
  
  # 언어별 설정
  language_specific:
    javascript:
      check_async_patterns: true
      check_console_statements: true
      detect_unused_variables: true
    
    python:
      check_pep8: true
      security_analysis: true
    
    markdown:
      check_links: true
      spell_check: false

# 보안 검사
security:
  secrets_detection: true
  dependency_check: true
  
# 코드 품질
quality:
  complexity_threshold: 10
  duplication_check: true
  function_length_threshold: 50
