# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
    
  include_patterns:
    - "**/*.{js,ts,jsx,tsx}"
    - "**/*.{py,java,go,cpp,c,cs}"
    - "**/*.{yml,yaml,json,md}"
  
  exclude_patterns:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "*.min.js"
    - "coverage/**"
    - "vendor/**"
    - ".git/**"

  request_changes_workflow: false
  base_branches:
    - "main"
    - "master"
    - "develop"

# 리뷰 설정
review_settings:
  thoroughness: "medium"
  
  focus_areas:
    - "security"
    - "performance" 
    - "maintainability"
    - "testing"
    - "documentation"
  
  # 언어별 설정
  language_specific:
    javascript:
      check_async_patterns: true
      check_console_statements: true
      detect_unused_variables: true
    
    python:
      check_pep8: true
      security_analysis: true
    
    markdown:
      check_links: true
      spell_check: false

# 보안 검사
security:
  secrets_detection: true
  dependency_check: true
  
# 코드 품질
quality:
  complexity_threshold: 10
  duplication_check: true
  function_length_threshold: 50

path_filters:
  - path_globs:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
      - "**/*.py"
      - "**/*.java"
      - "**/*.go"
      - "**/*.md"

chatops:
  chat:
    instructions: "Please review this code for security, performance, and maintainability."
