# Anteon 설정
alaz:
  enabled: true
  image:
    tag: "latest"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi

backend:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

frontend:
  enabled: true
  replicas: 1
  service:
    type: NodePort
    port: 8080

postgres:
  enabled: true
  auth:
    database: anteon
    username: anteon
    password: anteon123
