apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-platform-backend-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ai-platform-backend-role
subjects:
- kind: ServiceAccount
  name: ai-platform-backend-sa
  namespace: ai-platform
